### PR TITLE
Metadata about submission language versions

### PR DESCRIPTION
**Pull request by evouga**
Resolves https://github.com/Kattis/problem-package-format/issues/207

### CODE REVIEW

**Review by JoelNiemela — COMMENTED** [review]
Do we want to put this in `submissions.yaml`? `language_versions` might be used to describe which language version e.g. an output validator is written in.

**Comment by evouga** [comment]
Hmm good point, maybe we want this in problem.yaml instead?

**Comment by niemela** [comment]
> Hmm good point, maybe we want this in problem.yaml instead?

I think so.

This will certainly be *mostly* be useful for submissions, but *technically* it should really apply to all programs.

So... I'm a little bit torn, because it *almost* fits perfectly in `submission.yaml`... but I think it *should* be in `problem.yaml`.

**Comment by evouga** [comment]
Now in problem.yaml

**Review by niemela — APPROVED** [review]

**Comment by pehrsoderman** [comment]
Needs a rebase.

**Pull request closed without merging**
