### PR TITLE
Update examples to latest draft version

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
`problem.yaml`:
- add required `name`
- add version
- add uuid
- add new time limit settings

directory:
- less indentation
- clarify that `submissions/*` is currently about the final verdict
- rename `output_validators` to `output_validator`

### CODE REVIEW

**Comment by niemela** [comment]
Don't we need to have one of these per version?

**Comment by RagnarGrootKoerkamp** [comment]
Yeah not quite sure. Users should always use the latest version for new problems IMO, so not having examples for old versions discourages that.

But we could add examples for older versions if people feel like it.

**Comment by niemela** [comment]
> Users should always use the latest version for new problems IMO, so not having examples for old versions discourages that.

That's a really good point. So let's start with having good examples for the current version then. (i.e. what you're doing).

What do you think about having `2023-07-draft` either in the file name or at the top of the file so that it's very clear that the example is specifically for that version?

**Comment by RagnarGrootKoerkamp** [comment]
> What do you think about having `2023-07-draft` either in the file name or at the top of the file so that it's very clear that the example is specifically for that version?

yes done. Mentioned at top of directory example, and added  `problem_format_version: 2023-07-draft` also to the minimal `problem.yaml`.

**Review by niemela — APPROVED** [review]

**Pull request merged**
