### PR TITLE
Add run_samples option in testdata.yaml

### LINKED ISSUE #40: Invalid sample files
We had some problems with randomized solutions where we guarantee n=1000, but that is unpractical in teh samples, so we had those with much smaller n, eg n=10.

It would be nice to officially support samples that are only shown, but not run.

I implemented this with a `.{in,ans}.statement` extension, but open to other options.

### PR DESCRIPTION
**Pull request by Tagl**
Closes #40

### CODE REVIEW

**Review by RagnarGrootKoerkamp — APPROVED** [review]

**Comment by RagnarGrootKoerkamp** [comment]
domjudge does not support `input_validator_flags`, but it doesn't matter because domjudge anyway doesn't do input validation. Could you add some text so say that `samples` **will** be input_validated, and that `input_validator_flags` can be used to modify this.

**Comment by Tagl** [comment]
> Could you add some text so say that `samples` **will** be input_validated, and that `input_validator_flags` can be used to modify this.

Added

**Review by niemela — CHANGES_REQUESTED** [review]
`run_samples` should be listed in the table (just above the "Skipping Execution of Samples" section).

**Comment by Tagl** [comment]
> `run_samples` should be listed in the table (just above the "Skipping Execution of Samples" section).

Added

**Review by niemela — APPROVED** [review]

**Comment by niemela** [comment]
There is maybe some wordsmithing and restructuring I would want to do, but this is the meaning we have agreed on. Will merge shortly.

**Pull request merged**
